openjij: openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > > Class Template Reference
openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > > Class Template Reference
KLocalPolynomial class.
#include <k_local_polynomial.hpp>
Public Types
using system_type = classical_system
system type
Public Member Functions
KLocalPolynomial (const graph::Binaries &init_binaries, const graph::Polynomial< FloatType > &poly_graph)
Constructor of KLocalPolynomial system class.
KLocalPolynomial (const graph::Binaries &init_binaries, const nlohmann::json &j)
Constructor of KLocalPolynomial system class.
void reset_binaries (const graph::Binaries &init_binaries)
Reset KLocalPolynomial system with new binary configurations.
void reset_dE ()
Reset energy differences (dE), which is used to determine whether to flip the binary or not.
FloatType dE_single (const graph::Index index_binary) const
Return the energy difference of single spin flip update.
FloatType dE_k_local (const std::size_t index_key)
Return the energy difference of k-local update.
void update_system_k_local ()
Update binary configurations by k-local update.
void update_system_single (const graph::Index index_update_binary)
Flip specified binary by single spin flip.
void virtual_update_system_single (const graph::Index index_update_binary)
Virtually flip specified binary by single spin flip.
void reset_virtual_system ()
Reset binary configurations virtually updated by k-local update.
void set_rate_call_k_local (int rate_k_local)
Set "rate_call_k_local".
int64_t GetNumInteractions () const
Get the number of interactions.
int64_t GetZeroCount (const std::size_t index_key) const
Return the number of variables taking the zero in the interaction specified by "index_key".
FloatType GetPolyValue (const std::size_t index_key) const
Get the value of the interaction specified by "index_key".
const std::vector< graph::Index > & get_adj (const std::size_t index_binary) const
Get the adjacency list (the index of interactions) of the binary specified by "index_binary".
const std::vector< graph::Index > & get_active_binaries () const
Get "active_binaries_", which is the list of the binaries connected by at least one interaction.
FloatType get_max_effective_dE () const
Get "max_effective_dE_", which is a upper bound of energy gap.
FloatType get_min_effective_dE () const
Get "min_effective_dE_", which is a rough lower bound of energy gap.
const cimod::PolynomialValueList< FloatType > & get_values () const
Get the PolynomialValueList object, which is the list of the values of the polynomial interactions as std::vector<FloatType>.
const cimod::PolynomialKeyList< graph::Index > & get_keys () const
Get the PolynomialKeyList object, which is the list of the indices of the polynomial interactions as std::vector<std::vector<graph::Index>>.
const std::vector< std::vector< graph::Index > > & get_adj () const
Get the adjacency list, which is the list of the indices of polynomial interactions including specific binary.
std::string get_vartype_string () const
Get the vartype as std::string, which must be "BINARY".
Public Attributes
const int64_t num_binaries
The number of binaries.
int rate_call_k_local = 10
k-local update is activated per rate_call_k_local times
int64_t count_call_updater = 0
Counter of calling updater.
graph::Binaries binaries
Binary configurations.
const cimod::Vartype vartype = cimod::Vartype::BINARY
The model's type. SPIN or BINARY.
Private Member Functions
void SortInteractions ()
Sort interactions in accordance with its value and the degree of interactions (ascending order).
void SetAdj ()
Set adjacency list.
void ResetZeroCount ()
Set zero_count_ and zero_count_v_.
std::pair< std::vector< graph::Index >, FloatType > FindMaxInteraction () const
Return the key and value of the absolute maximum interaction.
std::pair< std::vector< graph::Index >, FloatType > FindMinInteraction (const FloatType threshold=0.0) const
Return the key and value of the absolute minimum interaction.
Private Attributes
int64_t num_interactions_
The number of the interactions.
std::vector< FloatType > dE_
The energy differences when flipping a binary.
std::vector< int64_t > zero_count_
The number of variables taking the zero in each interaction.
std::vector< std::vector< graph::Index > > adj_
Adjacency list, which is the list of the indices of polynomial interactions including specific binary.
cimod::PolynomialKeyList< graph::Index > poly_key_list_
The list of the indices of the polynomial interactions as std::vector<std::vector<graph::Index>>.
cimod::PolynomialValueList< FloatType > poly_value_list_
The list of the values of the polynomial interactions as std::vector<FloatType>.
std::vector< graph::Index > active_binaries_
The list of the binaries connected by at least one interaction.
FloatType max_effective_dE_
Upper bound of energy gap.
FloatType min_effective_dE_
Rough lower bound of energy gap.
std::vector< FloatType > dE_v_
The energy differences when flipping a binary, which is used to implement k-local update.
graph::Binaries binaries_v_
Virtually updated binary configulations, which is used to implement k-local update.
std::unordered_set< std::size_t > update_index_dE_v_
The list of virtually updated delta E's, which is used to implement k-local update.
std::vector< std::size_t > update_index_zero_count_v_
The list of virtually updated index of zero_count_v_, which is used to implement k-local update.
std::vector< std::size_t > update_index_binaries_v_
The list of virtually updated index of binaries_v_, which is used to implement k-local update.
std::vector< int64_t > zero_count_v_
The list of virtually updated the number of variables taking the zero in each interaction, which is used to implement k-local update.
Detailed Description
template<typename FloatType>
class openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >
KLocalPolynomial class.
Member Typedef Documentation
system_type
template<typename FloatType > using openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::system_type = classical_system
system type
Constructor & Destructor Documentation
KLocalPolynomial() [1/2]
template<typename FloatType > openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::KLocalPolynomial (const graph::Binaries & init_binaries, const graph::Polynomial< FloatType > & poly_graph) inline
Constructor of KLocalPolynomial system class.
Parameters
init_binaries const graph::Binaries&. The initial binary configurations.
poly_graph const graph::Polynomial<FloatType>& (Polynomial graph class). The initial interacrtions.
References openjij::graph::Polynomial< FloatType >::get_keys(), and openjij::graph::Polynomial< FloatType >::get_values().
KLocalPolynomial() [2/2]
template<typename FloatType > openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::KLocalPolynomial (const graph::Binaries & init_binaries, const nlohmann::json & j) inline
Constructor of KLocalPolynomial system class.
Parameters
init_binaries const graph::Binaries&. The initial binary configurations.
j const nlohmann::json&
References openjij::graph::json_parse().
Member Function Documentation
dE_k_local()
template<typename FloatType > FloatType openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::dE_k_local (const std::size_t index_key) inline
Return the energy difference of k-local update.
Note that this function changes the internal state of KLocalPolynomial system. This function virtually update the system by k-local update.
Parameters
index_key const graph::Index
Returns
the energy difference corresponding to "index_key"
dE_single()
template<typename FloatType > FloatType openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::dE_single (const graph::Index index_binary) const inline
Return the energy difference of single spin flip update.
Parameters
index_binary const graph::Index
Returns
the energy difference corresponding to "index_binary"
FindMaxInteraction()
template<typename FloatType > std::pair< std::vector< graph::Index >, FloatType > openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::FindMaxInteraction () const inline private
Return the key and value of the absolute maximum interaction.
Returns
The key and value of the absolute maximum interaction as std::pair.
FindMinInteraction()
template<typename FloatType > std::pair< std::vector< graph::Index >, FloatType > openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::FindMinInteraction (const FloatType threshold = 0.0) const inline private
Return the key and value of the absolute minimum interaction.
Returns
The key and value of the absolute minimum interaction as std::pair.
get_active_binaries()
template<typename FloatType > const std::vector< graph::Index > & openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::get_active_binaries () const inline
Get "active_binaries_", which is the list of the binaries connected by at least one interaction.
Returns
active_binaries_
get_adj() [1/2]
template<typename FloatType > const std::vector< std::vector< graph::Index > > & openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::get_adj () const inline
Get the adjacency list, which is the list of the indices of polynomial interactions including specific binary.
Returns
adjacency list
get_adj() [2/2]
template<typename FloatType > const std::vector< graph::Index > & openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::get_adj (const std::size_t index_binary) const inline
Get the adjacency list (the index of interactions) of the binary specified by "index_binary".
Parameters
index_binary const std::size_t
Returns
Corresponding adjacency list.
get_keys()
template<typename FloatType > const cimod::PolynomialKeyList< graph::Index > & openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::get_keys () const inline
Get the PolynomialKeyList object, which is the list of the indices of the polynomial interactions as std::vector<std::vector<graph::Index>>.
Returns
"poly_key_list_"
get_max_effective_dE()
template<typename FloatType > FloatType openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::get_max_effective_dE () const inline
Get "max_effective_dE_", which is a upper bound of energy gap.
Returns
max_effective_dE_
get_min_effective_dE()
template<typename FloatType > FloatType openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::get_min_effective_dE () const inline
Get "min_effective_dE_", which is a rough lower bound of energy gap.
Returns
min_effective_dE_
get_values()
template<typename FloatType > const cimod::PolynomialValueList< FloatType > & openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::get_values () const inline
Get the PolynomialValueList object, which is the list of the values of the polynomial interactions as std::vector<FloatType>.
Returns
"poly_value_list_"
get_vartype_string()
template<typename FloatType > std::string openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::get_vartype_string () const inline
Get the vartype as std::string, which must be "BINARY".
Returns
"BINARY" as std::string
GetNumInteractions()
template<typename FloatType > int64_t openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::GetNumInteractions () const inline
Get the number of interactions.
GetPolyValue()
template<typename FloatType > FloatType openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::GetPolyValue (const std::size_t index_key) const inline
Get the value of the interaction specified by "index_key".
Parameters
index_key const std::size_t
Returns
Corresponding value.
GetZeroCount()
template<typename FloatType > int64_t openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::GetZeroCount (const std::size_t index_key) const inline
Return the number of variables taking the zero in the interaction specified by "index_key".
Parameters
index_key const std::size_t
Returns
Corresponding number of variables taking the zero.
reset_binaries()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::reset_binaries (const graph::Binaries & init_binaries) inline
Reset KLocalPolynomial system with new binary configurations.
Parameters
init_binaries const graph::Binaries&
reset_dE()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::reset_dE () inline
Reset energy differences (dE), which is used to determine whether to flip the binary or not.
reset_virtual_system()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::reset_virtual_system () inline
Reset binary configurations virtually updated by k-local update.
ResetZeroCount()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::ResetZeroCount () inline private
Set zero_count_ and zero_count_v_.
set_rate_call_k_local()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::set_rate_call_k_local (int rate_k_local) inline
Set "rate_call_k_local".
k-local update is activated per rate_call_k_local times.
Parameters
rate_k_local int.
SetAdj()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::SetAdj () inline private
Set adjacency list.
Note that the list is sorted in accordance with the value of the interactions.
SortInteractions()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::SortInteractions () inline private
Sort interactions in accordance with its value and the degree of interactions (ascending order).
update_system_k_local()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::update_system_k_local () inline
Update binary configurations by k-local update.
update_system_single()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::update_system_single (const graph::Index index_update_binary) inline
Flip specified binary by single spin flip.
Parameters
index_update_binary const graph::Index
virtual_update_system_single()
template<typename FloatType > void openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::virtual_update_system_single (const graph::Index index_update_binary) inline
Virtually flip specified binary by single spin flip.
Parameters
index_update_binary const graph::Index.
Member Data Documentation
active_binaries_
template<typename FloatType > std::vector<graph::Index> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::active_binaries_ private
The list of the binaries connected by at least one interaction.
adj_
template<typename FloatType > std::vector<std::vector<graph::Index> > openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::adj_ private
Adjacency list, which is the list of the indices of polynomial interactions including specific binary.
binaries
template<typename FloatType > graph::Binaries openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::binaries
Binary configurations.
binaries_v_
template<typename FloatType > graph::Binaries openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::binaries_v_ private
Virtually updated binary configulations, which is used to implement k-local update.
count_call_updater
template<typename FloatType > int64_t openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::count_call_updater = 0
Counter of calling updater.
dE_
template<typename FloatType > std::vector<FloatType> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::dE_ private
The energy differences when flipping a binary.
dE_v_
template<typename FloatType > std::vector<FloatType> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::dE_v_ private
The energy differences when flipping a binary, which is used to implement k-local update.
-------------—The following member variables are used to virtually update
the system for k-local update-------------
max_effective_dE_
template<typename FloatType > FloatType openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::max_effective_dE_ private
Upper bound of energy gap.
min_effective_dE_
template<typename FloatType > FloatType openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::min_effective_dE_ private
Rough lower bound of energy gap.
num_binaries
template<typename FloatType > const int64_t openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::num_binaries
The number of binaries.
num_interactions_
template<typename FloatType > int64_t openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::num_interactions_ private
The number of the interactions.
-------------—The following functions are for debugging. Disable when
release.-------------
poly_key_list_
template<typename FloatType > cimod::PolynomialKeyList<graph::Index> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::poly_key_list_ private
The list of the indices of the polynomial interactions as std::vector<std::vector<graph::Index>>.
poly_value_list_
template<typename FloatType > cimod::PolynomialValueList<FloatType> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::poly_value_list_ private
The list of the values of the polynomial interactions as std::vector<FloatType>.
rate_call_k_local
template<typename FloatType > int openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::rate_call_k_local = 10
k-local update is activated per rate_call_k_local times
update_index_binaries_v_
template<typename FloatType > std::vector<std::size_t> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::update_index_binaries_v_ private
The list of virtually updated index of binaries_v_, which is used to implement k-local update.
update_index_dE_v_
template<typename FloatType > std::unordered_set<std::size_t> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::update_index_dE_v_ private
The list of virtually updated delta E's, which is used to implement k-local update.
update_index_zero_count_v_
template<typename FloatType > std::vector<std::size_t> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::update_index_zero_count_v_ private
The list of virtually updated index of zero_count_v_, which is used to implement k-local update.
vartype
template<typename FloatType > const cimod::Vartype openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::vartype = cimod::Vartype::BINARY
The model's type. SPIN or BINARY.
zero_count_
template<typename FloatType > std::vector<int64_t> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::zero_count_ private
The number of variables taking the zero in each interaction.
zero_count_v_
template<typename FloatType > std::vector<int64_t> openjij::system::KLocalPolynomial< graph::Polynomial< FloatType > >::zero_count_v_ private
The list of virtually updated the number of variables taking the zero in each interaction, which is used to implement k-local update.
The documentation for this class was generated from the following file:
k_local_polynomial.hpp