openjij: openjij.model.model Namespace Reference
openjij.model.model Namespace Reference
Functions
def make_BinaryQuadraticModel (dict linear, dict quadratic, sparse)
def make_BinaryQuadraticModel_from_JSON (dict obj)
def BinaryQuadraticModel (linear, quadratic, *args, **kwargs)
def bqm_from_numpy_matrix (mat, list variables=None, offset=0.0, vartype="BINARY", **kwargs)
def bqm_from_qubo (Q, offset=0.0, **kwargs)
def bqm_from_ising (linear, quadratic, offset=0.0, **kwargs)
def make_BinaryPolynomialModel (polynomial, index_type=None, tuple_size=0)
def make_BinaryPolynomialModel_from_JSON (obj)
def BinaryPolynomialModel (*args, **kwargs)
def _BinaryPolynomialModel_from_dict (dict polynomial, vartype)
def _BinaryPolynomialModel_from_list (list keys, list values, vartype)
def make_BinaryPolynomialModel_from_hising (*args, **kwargs)
def _make_BinaryPolynomialModel_from_hising_from_dict (dict polynomial)
def _make_BinaryPolynomialModel_from_hising_from_list (list keys, list values)
def make_BinaryPolynomialModel_from_hubo (*args, **kwargs)
def _make_BinaryPolynomialModel_from_hubo_from_dict (dict polynomial)
def _make_BinaryPolynomialModel_from_hubo_from_list (list keys, list values)
def _to_cxxcimod (vartype)
Variables
model_type
Function Documentation
_BinaryPolynomialModel_from_dict()
def openjij.model.model._BinaryPolynomialModel_from_dict (dict polynomial, vartype) private
References openjij.model.model._to_cxxcimod(), and openjij.model.model.make_BinaryPolynomialModel().
Referenced by openjij.model.model.BinaryPolynomialModel().
_BinaryPolynomialModel_from_list()
def openjij.model.model._BinaryPolynomialModel_from_list (list keys, list values, vartype) private
References openjij.model.model._to_cxxcimod(), and openjij.model.model.make_BinaryPolynomialModel().
Referenced by openjij.model.model.BinaryPolynomialModel().
_make_BinaryPolynomialModel_from_hising_from_dict()
def openjij.model.model._make_BinaryPolynomialModel_from_hising_from_dict (dict polynomial) private
References openjij.model.model.make_BinaryPolynomialModel().
Referenced by openjij.model.model.make_BinaryPolynomialModel_from_hising().
_make_BinaryPolynomialModel_from_hising_from_list()
def openjij.model.model._make_BinaryPolynomialModel_from_hising_from_list (list keys, list values) private
References openjij.model.model.make_BinaryPolynomialModel().
Referenced by openjij.model.model.make_BinaryPolynomialModel_from_hising().
_make_BinaryPolynomialModel_from_hubo_from_dict()
def openjij.model.model._make_BinaryPolynomialModel_from_hubo_from_dict (dict polynomial) private
References openjij.model.model.make_BinaryPolynomialModel().
Referenced by openjij.model.model.make_BinaryPolynomialModel_from_hubo().
_make_BinaryPolynomialModel_from_hubo_from_list()
def openjij.model.model._make_BinaryPolynomialModel_from_hubo_from_list (list keys, list values) private
References openjij.model.model.make_BinaryPolynomialModel().
Referenced by openjij.model.model.make_BinaryPolynomialModel_from_hubo().
_to_cxxcimod()
def openjij.model.model._to_cxxcimod (vartype) private
References openjij.model.model.make_BinaryPolynomialModel_from_hising(), openjij.model.model.make_BinaryPolynomialModel_from_hubo(), and openjij.model.model.make_BinaryPolynomialModel_from_JSON().
Referenced by openjij.model.model._BinaryPolynomialModel_from_dict(), openjij.model.model._BinaryPolynomialModel_from_list(), and openjij.model.model.BinaryPolynomialModel().
BinaryPolynomialModel()
def openjij.model.model.BinaryPolynomialModel (* args, ** kwargs)
References openjij.model.model._BinaryPolynomialModel_from_dict(), openjij.model.model._BinaryPolynomialModel_from_list(), and openjij.model.model._to_cxxcimod().
Referenced by openjij.sampler.base_sa_sample_hubo.base_sample_hubo(), and openjij.model.model.make_BinaryPolynomialModel().
BinaryQuadraticModel()
def openjij.model.model.BinaryQuadraticModel (linear, quadratic, * args, ** kwargs)
Generate BinaryQuadraticModel object.
Attributes:
    vartype (dimod.Vartype): variable type SPIN or BINARY
    linear (dict): represents linear term
    quadratic (dict): represents quadratic term
    offset (float): represents constant energy term when convert to SPIN from BINARY
    num_variables (int): represents number of variables in the model
    variables (list): represents variables of the binary quadratic model
Args:
    linear (dict): linear biases
    quadratic (dict): quadratic biases
    offset (float): offset
    vartype (openjij.variable_type.Vartype): vartype ('SPIN' or 'BINARY')
    kwargs:
Returns:
    generated BinaryQuadraticModel
Examples:
    BinaryQuadraticModel can be initialized by specifing h and J::
        >>> h = {0: 1, 1: -2}
        >>> J = {(0, 1): -1, (1, 2): -3, (2, 3): 0.5}
        >>> bqm = oj.BinaryQuadraticModel(self.h, self.J)
    You can also use strings and tuples of integers (up to 4 elements) as indices::
        >>> h = {'a': 1, 'b': -2}
        >>> J = {('a', 'b'): -1, ('b', 'c'): -3, ('c', 'd'): 0.5}
        >>> bqm = oj.BinaryQuadraticModel(self.h, self.J)
References openjij.model.model.make_BinaryQuadraticModel().
Referenced by openjij.model.model.make_BinaryQuadraticModel().
bqm_from_ising()
def openjij.model.model.bqm_from_ising (linear, quadratic, offset = 0.0, ** kwargs)
References openjij.model.model.make_BinaryQuadraticModel(), and openjij.model.model.make_BinaryQuadraticModel_from_JSON().
bqm_from_numpy_matrix()
def openjij.model.model.bqm_from_numpy_matrix (mat, list variables = None, offset = 0.0, vartype = "BINARY", ** kwargs)
References openjij.model.model.make_BinaryQuadraticModel().
bqm_from_qubo()
def openjij.model.model.bqm_from_qubo (Q, offset = 0.0, ** kwargs)
References openjij.model.model.make_BinaryQuadraticModel().
make_BinaryPolynomialModel()
def openjij.model.model.make_BinaryPolynomialModel (polynomial, index_type = None, tuple_size = 0)
References openjij.model.model.BinaryPolynomialModel().
Referenced by openjij.model.model._BinaryPolynomialModel_from_dict(), openjij.model.model._BinaryPolynomialModel_from_list(), openjij.model.model._make_BinaryPolynomialModel_from_hising_from_dict(), openjij.model.model._make_BinaryPolynomialModel_from_hising_from_list(), openjij.model.model._make_BinaryPolynomialModel_from_hubo_from_dict(), openjij.model.model._make_BinaryPolynomialModel_from_hubo_from_list(), and openjij.model.model.make_BinaryPolynomialModel_from_JSON().
make_BinaryPolynomialModel_from_hising()
def openjij.model.model.make_BinaryPolynomialModel_from_hising (* args, ** kwargs)
References openjij.model.model._make_BinaryPolynomialModel_from_hising_from_dict(), and openjij.model.model._make_BinaryPolynomialModel_from_hising_from_list().
Referenced by openjij.model.model._to_cxxcimod().
make_BinaryPolynomialModel_from_hubo()
def openjij.model.model.make_BinaryPolynomialModel_from_hubo (* args, ** kwargs)
References openjij.model.model._make_BinaryPolynomialModel_from_hubo_from_dict(), and openjij.model.model._make_BinaryPolynomialModel_from_hubo_from_list().
Referenced by openjij.model.model._to_cxxcimod().
make_BinaryPolynomialModel_from_JSON()
def openjij.model.model.make_BinaryPolynomialModel_from_JSON (obj)
References openjij.model.model.make_BinaryPolynomialModel().
Referenced by openjij.model.model._to_cxxcimod().
make_BinaryQuadraticModel()
def openjij.model.model.make_BinaryQuadraticModel (dict linear, dict quadratic, sparse)
BinaryQuadraticModel factory.
Returns:
    generated BinaryQuadraticModel class
References openjij.model.model.BinaryQuadraticModel().
Referenced by openjij.model.model.BinaryQuadraticModel(), openjij.model.model.bqm_from_ising(), openjij.model.model.bqm_from_numpy_matrix(), openjij.model.model.bqm_from_qubo(), openjij.model.model.make_BinaryQuadraticModel_from_JSON(), openjij.model.chimera_model.make_ChimeraModel(), and openjij.model.king_graph.make_KingGraph().
make_BinaryQuadraticModel_from_JSON()
def openjij.model.model.make_BinaryQuadraticModel_from_JSON (dict obj)
Make BinaryQuadraticModel from JSON.
Returns:
    corresponding BinaryQuadraticModel type
References openjij.model.model.make_BinaryQuadraticModel().
Referenced by openjij.model.model.bqm_from_ising().
Variable Documentation
model_type
openjij.model.model.model_type