openjij: fmath Namespace Reference
fmath Namespace Reference
Namespaces
local
Classes
class PowGenerator
Functions
float exp (float x)
double expd (double x)
__m128d exp_pd (__m128d x)
void expd_v (double *px, size_t n)
__m128 exp_ps (__m128 x)
float log (float x)
__m128 log_ps (__m128 x)
float log2 (float x)
float exp2 (float x)
__m128d log_pd (__m128d x)
__m128 pow_ps (__m128 x, __m128 y)
__m128d pow_pd (__m128d x, __m128d y)
Function Documentation
exp()
float fmath::exp (float x) inline
References fmath::local::C< EXP_N, LOG_N, EXPD_N >::expVar, fmath::local::ExpVar< N >::f88, and fmath::local::mask().
Referenced by openjij::updater::SingleSpinFlip< system::TransverseIsing< GraphType > >::do_calc(), exp2(), openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::Sparse< FloatType > > >::generate_poisson_points(), openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::generate_poisson_points(), openjij::updater::SingleFlipUpdater(), openjij::updater::SingleSpinFlip< system::ClassicalIsing< GraphType > >::update(), openjij::updater::SwendsenWang< system::ClassicalIsing< graph::Sparse< FloatType > > >::update(), openjij::updater::SwendsenWang< system::ClassicalIsing< graph::CSRSparse< FloatType > > >::update(), openjij::updater::KLocal< system::KLocalPolynomial< GraphType > >::update(), openjij::updater::SingleSpinFlip< system::ClassicalIsingPolynomial< GraphType > >::update_binary(), and openjij::updater::SingleSpinFlip< system::ClassicalIsingPolynomial< GraphType > >::update_spin().
exp2()
float fmath::exp2 (float x) inline
References exp().
exp_pd()
__m128d fmath::exp_pd (__m128d x) inline
References expd(), fmath::local::C< EXP_N, LOG_N, EXPD_N >::expdVar, fmath::local::mask(), and MIE_ALIGN.
Referenced by pow_pd().
exp_ps()
__m128 fmath::exp_ps (__m128 x) inline
References fmath::local::C< EXP_N, LOG_N, EXPD_N >::expVar.
Referenced by pow_ps().
expd()
double fmath::expd (double x) inline
References fmath::local::C< EXP_N, LOG_N, EXPD_N >::expdVar, and fmath::local::mask().
Referenced by exp_pd(), and expd_v().
expd_v()
void fmath::expd_v (double * px, size_t n) inline
References expd(), fmath::local::C< EXP_N, LOG_N, EXPD_N >::expdVar, and fmath::local::mask().
log()
float fmath::log (float x) inline
References fmath::local::C< EXP_N, LOG_N, EXPD_N >::logVar, and fmath::local::mask().
Referenced by log2(), log_pd(), fmath::local::LogVar< N >::LogVar(), openjij::sampler::SASampler< ModelType >::SetBetaMaxAuto(), openjij::sampler::SASampler< ModelType >::SetBetaMinAuto(), and openjij::updater::SingleSpinFlip< system::TransverseIsing< GraphType > >::update().
log2()
float fmath::log2 (float x) inline
References log().
log_pd()
__m128d fmath::log_pd (__m128d x) inline
References log().
Referenced by pow_pd().
log_ps()
__m128 fmath::log_ps (__m128 x) inline
References fmath::local::C< EXP_N, LOG_N, EXPD_N >::logVar, and MIE_PACK.
Referenced by pow_ps().
pow_pd()
__m128d fmath::pow_pd (__m128d x, __m128d y) inline
References exp_pd(), and log_pd().
pow_ps()
__m128 fmath::pow_ps (__m128 x, __m128 y) inline
References exp_ps(), and log_ps().