openjij: openjij.sampler.base_sa_sample_hubo Namespace Reference
openjij.sampler.base_sa_sample_hubo Namespace Reference
Functions
Response to_oj_response (list[list[Union[int, float]]] variables, list[Union[int, str, tuple[int,...]]] index_list, list[float] energies, str vartype)
Response base_sample_hubo (dict[tuple, float] hubo, Optional[str] vartype=None, int num_sweeps=1000, int num_reads=1, int num_threads=1, Optional[float] beta_min=None, Optional[float] beta_max=None, str update_method="METROPOLIS", str random_number_engine="XORSHIFT", Optional[int] seed=None, str temperature_schedule="GEOMETRIC")
Function Documentation
base_sample_hubo()
Response openjij.sampler.base_sa_sample_hubo.base_sample_hubo (dict[tuple, float] hubo, Optional[str] vartype = None, int num_sweeps = 1000, int num_reads = 1, int num_threads = 1, Optional[float] beta_min = None, Optional[float] beta_max = None, str update_method = "METROPOLIS", str random_number_engine = "XORSHIFT", Optional[int] seed = None, str temperature_schedule = "GEOMETRIC")
References openjij.model.model.BinaryPolynomialModel(), openjij.utils.cxx_cast.cast_to_cxx_random_number_engine(), openjij.utils.cxx_cast.cast_to_cxx_temperature_schedule(), openjij.utils.cxx_cast.cast_to_cxx_update_method(), openjij::sampler.make_sa_sampler(), and openjij.sampler.base_sa_sample_hubo.to_oj_response().
Referenced by openjij.sampler.sa_sampler.SASampler.sample_hubo().
to_oj_response()
Response openjij.sampler.base_sa_sample_hubo.to_oj_response (list[list[Union[int, float]]] variables, list[Union[int, str, tuple[int, ...]]] index_list, list[float] energies, str vartype)
Referenced by openjij.sampler.base_sa_sample_hubo.base_sample_hubo().