openjij: openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > > Struct Template Reference
openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > > Struct Template Reference
Continuous Time Swendsen Wang updater for CTQIsystem on CSR Sparse graph.
#include <continuous_time_swendsen_wang.hpp>
Public Types
using CTIsing = system::ContinuousTimeIsing< graph::CSRSparse< FloatType > >
using GraphType = typename graph::CSRSparse< FloatType >
using CutPoint = typename system::ContinuousTimeIsing< GraphType >::CutPoint
using TimeType = typename system::ContinuousTimeIsing< GraphType >::TimeType
Static Public Member Functions
template<typename RandomNumberEngine >
static void update (system::ContinuousTimeIsing< GraphType > &system, RandomNumberEngine &random_number_engine, const utility::TransverseFieldUpdaterParameter &parameter)
continuous time Swendsen-Wang updater for transverse ising model
static std::vector< CutPoint > create_timeline (const std::vector< CutPoint > &old_timeline, const std::vector< TimeType > &cuts)
create new timeline; place kinks by ignoring old cuts and place new cuts
static std::vector< CutPoint > create_timeline_easy (const std::vector< CutPoint > &old_timeline, const std::vector< TimeType > &cuts)
easy but inefficient version of create_timeline()
template<typename RandomNumberEngine >
static std::vector< TimeType > generate_poisson_points (const TimeType lambda, const TimeType beta, RandomNumberEngine &random_number_engine)
generates Poisson points with density lambda in the range of [0:beta)
Detailed Description
template<typename FloatType>
struct openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >
Continuous Time Swendsen Wang updater for CTQIsystem on CSR Sparse graph.
Template Parameters
FloatType
Member Typedef Documentation
CTIsing
template<typename FloatType > using openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::CTIsing = system::ContinuousTimeIsing<graph::CSRSparse<FloatType> >
CutPoint
template<typename FloatType > using openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::CutPoint = typename system::ContinuousTimeIsing<GraphType>::CutPoint
GraphType
template<typename FloatType > using openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::GraphType = typename graph::CSRSparse<FloatType>
TimeType
template<typename FloatType > using openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::TimeType = typename system::ContinuousTimeIsing<GraphType>::TimeType
Member Function Documentation
create_timeline()
template<typename FloatType > static std::vector<CutPoint> openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::create_timeline (const std::vector< CutPoint > & old_timeline, const std::vector< TimeType > & cuts) inline static
create new timeline; place kinks by ignoring old cuts and place new cuts
create_timeline_easy()
template<typename FloatType > static std::vector<CutPoint> openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::create_timeline_easy (const std::vector< CutPoint > & old_timeline, const std::vector< TimeType > & cuts) inline static
easy but inefficient version of create_timeline()
generate_poisson_points()
template<typename FloatType > template<typename RandomNumberEngine > static std::vector<TimeType> openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::generate_poisson_points (const TimeType lambda, const TimeType beta, RandomNumberEngine & random_number_engine) inline static
generates Poisson points with density lambda in the range of [0:beta)
Note
might be better to move this function to utility
References fmath::exp().
update()
template<typename FloatType > template<typename RandomNumberEngine > static void openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::update (system::ContinuousTimeIsing< GraphType > & system, RandomNumberEngine & random_number_engine, const utility::TransverseFieldUpdaterParameter & parameter) inline static
continuous time Swendsen-Wang updater for transverse ising model
References openjij::utility::UpdaterParameter< system::transverse_field_system >::beta, openjij::utility::UnionFind::find_set(), openjij::utility::UpdaterParameter< system::transverse_field_system >::s, and openjij::utility::UnionFind::unite_sets().
The documentation for this struct was generated from the following file:
continuous_time_swendsen_wang.hpp