openjij: openjij::utility::UnionFind Struct Reference
openjij::utility::UnionFind Struct Reference
#include <union_find.hpp>
Public Types
using Node = std::size_t
using Parent = std::vector< Node >
using Rank = std::vector< Node >
using size_type = Parent::size_type
Public Member Functions
UnionFind (size_type n)
void unite_sets (Node x, Node y)
Node find_set (Node node)
Parent get_roots () const
Private Attributes
Parent _parent
Rank _rank
Member Typedef Documentation
Node
using openjij::utility::UnionFind::Node = std::size_t
Parent
using openjij::utility::UnionFind::Parent = std::vector<Node>
Rank
using openjij::utility::UnionFind::Rank = std::vector<Node>
size_type
using openjij::utility::UnionFind::size_type = Parent::size_type
Constructor & Destructor Documentation
UnionFind()
openjij::utility::UnionFind::UnionFind (size_type n) inline explicit
References _parent.
Member Function Documentation
find_set()
Node openjij::utility::UnionFind::find_set (Node node) inline
References _parent.
Referenced by unite_sets(), openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::Sparse< FloatType > > >::update(), and openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::update().
get_roots()
Parent openjij::utility::UnionFind::get_roots () const inline
References _parent.
unite_sets()
void openjij::utility::UnionFind::unite_sets (Node x, Node y) inline
References _parent, _rank, and find_set().
Referenced by openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::Sparse< FloatType > > >::update(), and openjij::updater::ContinuousTimeSwendsenWang< system::ContinuousTimeIsing< graph::CSRSparse< FloatType > > >::update().
Member Data Documentation
_parent
Parent openjij::utility::UnionFind::_parent private
Referenced by find_set(), get_roots(), UnionFind(), and unite_sets().
_rank
Rank openjij::utility::UnionFind::_rank private
Referenced by unite_sets().
The documentation for this struct was generated from the following file:
union_find.hpp